name: Kubernetes CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Compile Python
        run: |
          python -m compileall app

      - name: Build Docker image
        run: |
          docker build -t k8s-cicd-demo:${{ github.sha }} ./app

      - name: Create Kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: ci-cluster

      - name: Load Docker image into Kind
        run: |
          kind load docker-image k8s-cicd-demo:${{ github.sha }} \
            --name ci-cluster

      - name: Update Kubernetes image
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|k8s-cicd-demo:${{ github.sha }}|g" \
            k8s/backend-deployment.yaml

      - name: Deploy namespace
        run: |
          kubectl apply -f k8s/namespace.yaml

      - name: Deploy PostgreSQL
        run: |
          kubectl apply -f k8s/postgres-secret.yaml
          kubectl apply -f k8s/postgres-pvc.yaml
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/postgres-service.yaml

      - name: Deploy backend configuration
        run: |
          kubectl apply -f k8s/backend-configmap.yaml
          kubectl apply -f k8s/backend-secret.yaml

      - name: Deploy backend
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml

      - name: Wait for PostgreSQL
        run: |
          kubectl rollout status deployment/postgres \
            -n demo \
            --timeout=120s

      - name: Wait for backend
        run: |
          kubectl rollout status deployment/backend \
            -n demo \
            --timeout=120s

      - name: Verify Kubernetes resources
        run: |
          kubectl get pods -n demo
          kubectl get services -n demo
          kubectl get deployments -n demo